name: Build Maven App2

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Maven Compile
      run: mvn compile

    - name: Maven Test
      run: mvn test

    - name: Build with Maven
      run: mvn package --file pom.xml

    
